export interface MCAFunder {
  id: string
  name: string
  logo: string
  verified: boolean
  claimed: boolean
  fileType: string
  maxFunding: number | null
  onboardingISOs: boolean
  description?: string
  minCreditScore?: number
  minTimeInBusiness?: number
  fundingSpeed?: number
  industries?: string[]
  factorRates?: {
    min: number
    max: number
  }
  termLength?: {
    min: number
    max: number
  }
  website?: string
  contactEmail?: string
  contactPhone?: string
  location?: string
}

export const mcaFunders: MCAFunder[] = [
  {
    id: "cfg-merchant-solutions",
    name: "CFG Merchant Solutions",
    logo: "/placeholder.svg?height=48&width=48&text=CFG",
    verified: true,
    claimed: true,
    fileType: "B-C",
    maxFunding: 500000,
    onboardingISOs: true,
    description:
      "CFG Merchant Solutions provides flexible funding solutions for small to medium-sized businesses across various industries.",
    minCreditScore: 550,
    minTimeInBusiness: 6,
    fundingSpeed: 2,
    industries: ["Retail", "Restaurants", "Healthcare", "Construction"],
    factorRates: {
      min: 1.15,
      max: 1.45,
    },
    termLength: {
      min: 3,
      max: 18,
    },
    website: "https://cfgmerchantsolutions.com",
    contactEmail: "info@cfgmerchantsolutions.com",
    contactPhone: "888-123-4567",
    location: "New York, NY",
  },
  {
    id: "stafford-business-funding",
    name: "Stafford Business Funding",
    logo: "/placeholder.svg?height=48&width=48&text=SBF",
    verified: true,
    claimed: true,
    fileType: "C-D",
    maxFunding: 15000,
    onboardingISOs: true,
    description:
      "Stafford Business Funding specializes in small business funding with minimal requirements and fast approval times.",
    minCreditScore: 500,
    minTimeInBusiness: 3,
    fundingSpeed: 1,
    industries: ["Retail", "Services", "Construction"],
    factorRates: {
      min: 1.18,
      max: 1.4,
    },
    termLength: {
      min: 3,
      max: 12,
    },
    website: "https://staffordbusinessfunding.com",
    contactEmail: "info@staffordbusinessfunding.com",
    contactPhone: "877-456-7890",
    location: "Dallas, TX",
  },
  {
    id: "thoro-corp",
    name: "Thoro Corp",
    logo: "/placeholder.svg?height=48&width=48&text=TC",
    verified: true,
    claimed: true,
    fileType: "B-C",
    maxFunding: 5000000,
    onboardingISOs: true,
    description:
      "Thoro Corp offers high-limit funding solutions for established businesses with substantial revenue streams.",
    minCreditScore: 600,
    minTimeInBusiness: 12,
    fundingSpeed: 3,
    industries: ["Healthcare", "Manufacturing", "Technology", "Wholesale"],
    factorRates: {
      min: 1.12,
      max: 1.35,
    },
    termLength: {
      min: 6,
      max: 24,
    },
    website: "https://thorocorp.com",
    contactEmail: "funding@thorocorp.com",
    contactPhone: "866-789-0123",
    location: "Chicago, IL",
  },
  {
    id: "viking-funding",
    name: "Viking Funding",
    logo: "/placeholder.svg?height=48&width=48&text=VF",
    verified: true,
    claimed: true,
    fileType: "B-D",
    maxFunding: 50000,
    onboardingISOs: true,
    description:
      "Viking Funding provides quick access to capital for small businesses with flexible repayment options.",
    minCreditScore: 520,
    minTimeInBusiness: 3,
    fundingSpeed: 1,
    industries: ["Retail", "Restaurants", "Services"],
    factorRates: {
      min: 1.2,
      max: 1.49,
    },
    termLength: {
      min: 3,
      max: 12,
    },
    website: "https://vikingfunding.com",
    contactEmail: "info@vikingfunding.com",
    contactPhone: "855-234-5678",
    location: "Minneapolis, MN",
  },
  {
    id: "big-blackbridge-investment-group",
    name: "BIG (Blackbridge Investment Group)",
    logo: "/placeholder.svg?height=48&width=48&text=BIG",
    verified: true,
    claimed: true,
    fileType: "B-C",
    maxFunding: null,
    onboardingISOs: true,
    description:
      "Blackbridge Investment Group specializes in custom funding solutions for businesses across multiple industries.",
    minCreditScore: 580,
    minTimeInBusiness: 6,
    fundingSpeed: 2,
    industries: ["Healthcare", "Technology", "Professional Services"],
    factorRates: {
      min: 1.15,
      max: 1.4,
    },
    termLength: {
      min: 6,
      max: 18,
    },
    website: "https://blackbridgeinvestmentgroup.com",
    contactEmail: "info@biginvest.com",
    contactPhone: "844-345-6789",
    location: "Atlanta, GA",
  },
  {
    id: "capital-domain",
    name: "Capital Domain",
    logo: "/placeholder.svg?height=48&width=48&text=CD",
    verified: true,
    claimed: true,
    fileType: "A-C",
    maxFunding: 1000000,
    onboardingISOs: true,
    description: "Capital Domain offers premium funding solutions with competitive rates for established businesses.",
    minCreditScore: 600,
    minTimeInBusiness: 12,
    fundingSpeed: 2,
    industries: ["Healthcare", "Manufacturing", "Technology", "Professional Services"],
    factorRates: {
      min: 1.1,
      max: 1.35,
    },
    termLength: {
      min: 6,
      max: 24,
    },
    website: "https://capitaldomain.com",
    contactEmail: "funding@capitaldomain.com",
    contactPhone: "833-456-7890",
    location: "Boston, MA",
  },
  {
    id: "capitawize",
    name: "Capitawize",
    logo: "/placeholder.svg?height=48&width=48&text=CW",
    verified: true,
    claimed: true,
    fileType: "B-D",
    maxFunding: null,
    onboardingISOs: true,
    description: "Capitawize provides flexible funding solutions with a focus on technology-driven approval processes.",
    minCreditScore: 550,
    minTimeInBusiness: 6,
    fundingSpeed: 1,
    industries: ["Retail", "Restaurants", "Services", "E-commerce"],
    factorRates: {
      min: 1.18,
      max: 1.45,
    },
    termLength: {
      min: 3,
      max: 18,
    },
    website: "https://capitawize.com",
    contactEmail: "info@capitawize.com",
    contactPhone: "877-567-8901",
    location: "San Francisco, CA",
  },
  {
    id: "everest-business-funding",
    name: "Everest Business Funding",
    logo: "/placeholder.svg?height=48&width=48&text=EBF",
    verified: true,
    claimed: true,
    fileType: "B-C",
    maxFunding: 500000,
    onboardingISOs: true,
    description: "Everest Business Funding offers merchant cash advances with competitive rates and flexible terms.",
    minCreditScore: 550,
    minTimeInBusiness: 6,
    fundingSpeed: 2,
    industries: ["Retail", "Restaurants", "Healthcare", "Services"],
    factorRates: {
      min: 1.15,
      max: 1.4,
    },
    termLength: {
      min: 4,
      max: 18,
    },
    website: "https://everestbusinessfunding.com",
    contactEmail: "info@everestbusinessfunding.com",
    contactPhone: "888-678-9012",
    location: "Miami, FL",
  },
  {
    id: "hunter-caroline",
    name: "Hunter Caroline",
    logo: "/placeholder.svg?height=48&width=48&text=HC",
    verified: true,
    claimed: true,
    fileType: "B-C",
    maxFunding: 1000000,
    onboardingISOs: true,
    description:
      "Hunter Caroline specializes in merchant cash advances for businesses in various positions, including stacking opportunities.",
    minCreditScore: 550,
    minTimeInBusiness: 6,
    fundingSpeed: 2,
    industries: ["Retail", "Restaurants", "Healthcare", "Construction", "Transportation"],
    factorRates: {
      min: 1.15,
      max: 1.45,
    },
    termLength: {
      min: 4,
      max: 12,
    },
    website: "https://huntercaroline.com",
    contactEmail: "info@huntercaroline.com",
    contactPhone: "866-789-0123",
    location: "New York, NY",
  },
  {
    id: "lendini",
    name: "Lendini",
    logo: "/placeholder.svg?height=48&width=48&text=LI",
    verified: true,
    claimed: true,
    fileType: "B-D",
    maxFunding: 300000,
    onboardingISOs: true,
    description: "Lendini provides fast and flexible funding solutions for small to medium-sized businesses.",
    minCreditScore: 530,
    minTimeInBusiness: 3,
    fundingSpeed: 1,
    industries: ["Retail", "Restaurants", "Services"],
    factorRates: {
      min: 1.18,
      max: 1.45,
    },
    termLength: {
      min: 3,
      max: 15,
    },
    website: "https://lendini.com",
    contactEmail: "funding@lendini.com",
    contactPhone: "855-890-1234",
    location: "Los Angeles, CA",
  },
  {
    id: "liquidibee",
    name: "Liquidibee",
    logo: "/placeholder.svg?height=48&width=48&text=LB",
    verified: true,
    claimed: true,
    fileType: "B-D",
    maxFunding: null,
    onboardingISOs: true,
    description: "Liquidibee offers fast merchant cash advances with minimal documentation requirements.",
    minCreditScore: 500,
    minTimeInBusiness: 3,
    fundingSpeed: 1,
    industries: ["Retail", "Services", "Transportation"],
    factorRates: {
      min: 1.2,
      max: 1.49,
    },
    termLength: {
      min: 3,
      max: 12,
    },
    website: "https://liquidibee.com",
    contactEmail: "info@liquidibee.com",
    contactPhone: "877-901-2345",
    location: "Denver, CO",
  },
  {
    id: "smart-business-funding",
    name: "Smart Business Funding",
    logo: "/placeholder.svg?height=48&width=48&text=SBF",
    verified: true,
    claimed: true,
    fileType: "A-D",
    maxFunding: 2000000,
    onboardingISOs: false,
    description: "Smart Business Funding provides high-limit funding solutions with flexible approval criteria.",
    minCreditScore: 550,
    minTimeInBusiness: 6,
    fundingSpeed: 2,
    industries: ["Healthcare", "Technology", "Manufacturing", "Professional Services"],
    factorRates: {
      min: 1.12,
      max: 1.4,
    },
    termLength: {
      min: 6,
      max: 24,
    },
    website: "https://smartbusinessfunding.com",
    contactEmail: "info@smartbusinessfunding.com",
    contactPhone: "866-012-3456",
    location: "Seattle, WA",
  },
  {
    id: "spartan-capital",
    name: "Spartan Capital",
    logo: "/placeholder.svg?height=48&width=48&text=SC",
    verified: true,
    claimed: true,
    fileType: "A-D",
    maxFunding: 1000000,
    onboardingISOs: true,
    description:
      "Spartan Capital specializes in merchant cash advances with no STIPS under $20K and flexible approval criteria.",
    minCreditScore: 500,
    minTimeInBusiness: 1,
    fundingSpeed: 1,
    industries: ["Retail", "Restaurants", "Services", "Construction"],
    factorRates: {
      min: 1.15,
      max: 1.45,
    },
    termLength: {
      min: 3,
      max: 15,
    },
    website: "https://spartancapital.com",
    contactEmail: "funding@spartancapital.com",
    contactPhone: "888-123-4567",
    location: "Phoenix, AZ",
  },
  {
    id: "1st-alliance-group",
    name: "1st Alliance Group LLC",
    logo: "/placeholder.svg?height=48&width=48&text=1AG",
    verified: true,
    claimed: true,
    fileType: "B-C",
    maxFunding: null,
    onboardingISOs: true,
    description: "1st Alliance Group provides merchant cash advances with competitive rates and flexible terms.",
    minCreditScore: 550,
    minTimeInBusiness: 6,
    fundingSpeed: 2,
    industries: ["Retail", "Restaurants", "Healthcare", "Services"],
    factorRates: {
      min: 1.15,
      max: 1.4,
    },
    termLength: {
      min: 4,
      max: 18,
    },
    website: "https://1stalliancegroup.com",
    contactEmail: "info@1stalliancegroup.com",
    contactPhone: "877-234-5678",
    location: "Philadelphia, PA",
  },
  {
    id: "1st-merchant-funding",
    name: "1st Merchant Funding",
    logo: "/placeholder.svg?height=48&width=48&text=1MF",
    verified: false,
    claimed: false,
    fileType: "B-C",
    maxFunding: 250000,
    onboardingISOs: false,
    description: "1st Merchant Funding offers merchant cash advances for small to medium-sized businesses.",
    minCreditScore: 550,
    minTimeInBusiness: 6,
    fundingSpeed: 2,
    industries: ["Retail", "Restaurants", "Services"],
    factorRates: {
      min: 1.18,
      max: 1.45,
    },
    termLength: {
      min: 3,
      max: 15,
    },
    website: "https://1stmerchantfunding.com",
    contactEmail: "info@1stmerchantfunding.com",
    contactPhone: "866-345-6789",
    location: "Orlando, FL",
  },
  {
    id: "501-advance",
    name: "501 Advance",
    logo: "/placeholder.svg?height=48&width=48&text=501",
    verified: true,
    claimed: true,
    fileType: "A-C",
    maxFunding: 300000,
    onboardingISOs: true,
    description: "501 Advance provides merchant cash advances with competitive rates and flexible terms.",
    minCreditScore: 550,
    minTimeInBusiness: 6,
    fundingSpeed: 2,
    industries: ["Retail", "Restaurants", "Healthcare", "Services"],
    factorRates: {
      min: 1.15,
      max: 1.4,
    },
    termLength: {
      min: 4,
      max: 18,
    },
    website: "https://501advance.com",
    contactEmail: "info@501advance.com",
    contactPhone: "888-456-7890",
    location: "Austin, TX",
  },
]

